### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by flannelhead** [sobotka/AgX-S2O3#1]
Hi @sobotka,

I am working on image formation for [darktable](https://www.darktable.org/) and am experimenting with a similar setup as AgX there. If I ever ends up in a useful state that could even be adopted in the software, it would be nice to cite your work in the codebase. I am not sure if it would count as a derivative work of this repo, but to avoid any confusion, would you be willing to release the work in this repo under an open source license (i.e. add a LICENSE file to the repo)?

It is surely amazing how simple yet effective the approach chosen for AgX is.

Best regards,
Sakari

**Comment by sobotka** [comment]
Fill your boots.

Placing licenses into things crosses ethical lines that are problematic. It’s a design concept for a given set of design constraints.

Pixar implemented Filmic into Renderman without an explicitly declared license.

**Comment by flannelhead** [comment]
Thanks for the reply. :) All clear.
